version: "3.3"
services:
  apache:
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
        my_net:
          ipv4_address: 172.18.1.2
    ports:
      - "1122:80"
    

  database:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
        my_net:
         ipv4_address: 172.18.1.3
    ports:
      - "3306:3306"
    environment:
      USER: jaya
      PASSWORD: 123
      PASS: pass
networks:
  my_net:
    driver: bridge
    ipam:     
      config:
        - subnet: 172.18.1.0/24      

